### ISSUE TITLE
Add QR code to stores / listings

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar.com#72]
Reddit user /r/vendanto made the following suggestion:

https://www.reddit.com/r/OpenBazaar/comments/ahcgsx/openbazaar_megathread_post_bugs_troubleshooting/eedbskj/

>With showing a QR code which I can scan with the Haven app, on the place where it states "buy now", I might be able to pay this product by using the Haven app.

Adding a QR code onto stores / listings on the site would allow users to easily navigate to them on mobile applications which understand the address scheme.

**Comment by hoffmabc** [comment]
Done.
