### ISSUE TITLE
Wrong scroll setting on featured stores

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar.com#73]
![image](https://user-images.githubusercontent.com/794517/51494231-92a64b00-1d7d-11e9-92b6-7f3ea6f5eb5f.png)

The faded scroll bars are still visible when scrolling is not necessary.

Changing `overflow: scroll` to `overflow-y: auto` would make it so only a horizontal scroll bar will appear if the content demands it.

**Comment by hoffmabc** [comment]
Thanks fixed
