### ISSUE TITLE
How to run this repository on my local computer?

### ISSUE THREAD

**Issue by gitkiwikiwi** [OpenBazaar/openbazaar.com#75]
Why can't  I see any docs for developer for openbazaar.com this site? Curious that how the database work? How to query data from different nodes of users.

**Comment by hoffmabc** [comment]
We didn't really design this as a site that others would run on their own. I can see about getting more information in here to help other's run it.

**Comment by hoffmabc** [comment]
You can create the database using this script (https://github.com/OpenBazaar/openbazaar.com/blob/master/scripts/create_database.sql) and then you'll have to configure it in `/application/config/database.php`

**Comment by Cam-B** [comment]
Thanks for the added instructions for the database @hoffmabc 

Could you please also add any instructions on how to update "featured stores" on the frontpage?

**Comment by Cam-B** [comment]
> We didn't really design this as a site that others would run on their own. 
More web instances = more overall exposure to the project

I'm really happy to see OB still chugging after all these years.

**Comment by hoffmabc** [comment]
Featured stores are configured here https://github.com/OpenBazaar/openbazaar.com/blob/86d3b2b78381bef264827d4645d6cbb8f144e4da/application/helpers/utility_helper.php#L3

**Comment by Cam-B** [comment]
Awesome. Thank you for the quick reply @hoffmabc !

**Comment by Cam-B** [comment]
Another question came up

It appears we can't add alternate listing explorer/search  providers
https://cloud.odat.xyz/s/7Jacd3fNEiomSom/preview

Is this by design, or how would we do this?

**Comment by hoffmabc** [comment]
You cannot add new search providers, but you probably could just change the URL of the search engine in the code when you deploy yourself.
