### ISSUE TITLE
Removed the fixed scrolling on the download bar, header and footer

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar.com#81]
These elements don't need to be fixed while scrolling.

**Comment by hoffmabc** [comment]
Sorry can I have a little more description here @morebrownies ? You don't want these elements to be fixed?

**Comment by morebrownies** [comment]
Correct, nothing should be set to fixed while scrolling.

**Comment by hoffmabc** [comment]
@morebrownies i'm going to have to disagree here not on style but UX. With the infinite scroll on the page it will always be unclickable and unviewable.
